// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WMS.Persistence.Configuration;

#nullable disable

namespace WMS.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221203234111_DistributionCenterAddUnique")]
    partial class DistributionCenterAddUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WMS.Domain.DistributionCenter.DistributionCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("internal_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_distribution_center");

                    b.HasIndex("Document")
                        .IsUnique()
                        .HasDatabaseName("ix_distribution_center_document");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ix_distribution_center_internal_code");

                    b.HasIndex("InternalCode", "Document")
                        .IsUnique()
                        .HasDatabaseName("ix_distribution_center_internal_code_document");

                    b.ToTable("distribution_center", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
